[package]
name = "perf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
rustls = { version = "0.20", default-features = false, features = ["dangerous_configuration"] }
rustls-pemfile = "1.0.0"
rcgen = "0.10.0"
bytes = "1"
mio = {  version="0.8.5", features=["net"] }
quinn = "0.9.3"
quinn-proto = "0.9.2"
serde = { version="1.0.152", features=["derive"] }
serde_json = "1.0.91"
socket2 = "0.4.7"
#libc = "0.2.139"
futures = "0.3"

#[profile.release]
#strip = true
#codegen-units = 1
#lto = true
#opt-level = "z"
#panic = "abort"
