[package]
name = "perf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
tokio = { version="1.25.0", features=["net", "macros", "rt", "rt-multi-thread"] }
mio = "0.8.5"
serde = { version="1.0.152", features=["derive"] }
serde_json = "1.0.91"
libc = "0.2.139"
socket2 = "0.4.7"
chrono = "0.4.23"
